# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valuedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(191, 208)
        Dialog.setMinimumSize(QtCore.QSize(191, 208))
        Dialog.setMaximumSize(QtCore.QSize(191, 208))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.Dlcd = QtWidgets.QLCDNumber(Dialog)
        self.Dlcd.setSmallDecimalPoint(False)
        self.Dlcd.setDigitCount(5)
        self.Dlcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.Dlcd.setProperty("value", 65535.0)
        self.Dlcd.setProperty("intValue", 65535)
        self.Dlcd.setObjectName("Dlcd")
        self.gridLayout.addWidget(self.Dlcd, 0, 0, 1, 2)
        self.DsB = QtWidgets.QSpinBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.DsB.setFont(font)
        self.DsB.setMaximum(65535)
        self.DsB.setProperty("value", 65535)
        self.DsB.setObjectName("DsB")
        self.gridLayout.addWidget(self.DsB, 1, 0, 1, 2)
        self.DhS = QtWidgets.QSlider(Dialog)
        self.DhS.setOrientation(QtCore.Qt.Horizontal)
        self.DhS.setObjectName("DhS")
        self.gridLayout.addWidget(self.DhS, 2, 0, 1, 2)
        self.DtB1 = QtWidgets.QToolButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DtB1.setFont(font)
        self.DtB1.setObjectName("DtB1")
        self.gridLayout.addWidget(self.DtB1, 3, 0, 1, 1)
        self.DtB2 = QtWidgets.QToolButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DtB2.setFont(font)
        self.DtB2.setObjectName("DtB2")
        self.gridLayout.addWidget(self.DtB2, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.DtB1.setText(_translate("Dialog", "确定"))
        self.DtB2.setText(_translate("Dialog", "取消"))
