# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_text2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1215, 684)
        Dialog.setMinimumSize(QtCore.QSize(1215, 684))
        Dialog.setMaximumSize(QtCore.QSize(1215, 684))
        self.tE = QtWidgets.QTextEdit(Dialog)
        self.tE.setGeometry(QtCore.QRect(0, 0, 1215, 684))
        self.tE.setMinimumSize(QtCore.QSize(1215, 684))
        self.tE.setMaximumSize(QtCore.QSize(1215, 684))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tE.setFont(font)
        self.tE.setStyleSheet("border-image: url(:/pic/1 (29).jpg);")
        self.tE.setObjectName("tE")
        self.tB2 = QtWidgets.QToolButton(Dialog)
        self.tB2.setGeometry(QtCore.QRect(1178, 0, 37, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tB2.setFont(font)
        self.tB2.setAutoRaise(True)
        self.tB2.setObjectName("tB2")
        self.tB1 = QtWidgets.QToolButton(Dialog)
        self.tB1.setGeometry(QtCore.QRect(1113, 0, 65, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tB1.setFont(font)
        self.tB1.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.tB1.setAutoRaise(True)
        self.tB1.setObjectName("tB1")

        self.retranslateUi(Dialog)
        self.tB1.clicked.connect(Dialog.accept)
        self.tB2.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "输入要传送的文本"))
        self.tE.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.tE.setPlaceholderText(_translate("Dialog", "输入"))
        self.tB2.setText(_translate("Dialog", "X"))
        self.tB1.setText(_translate("Dialog", "确认"))
import qrc_text2
